language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: heroku
  api_key:
    secure: PDRk/m6ENLnpLZ0sPqkR6uwF70R+Fk6LEEOn44dpseWMU60y9LD2nPXYk+gKUABz0kNjQEpKt7OfwcRVrj5AJLCzeKsEHEiq9cCPYJRgMriHUIyxwcAHVuXw2gM8lKZ6rccrYsPUoz0G2fWVk5ZTRFuN1rKT9nG0ZNKUUDlRVyVkdGl/QKOoVWExYi9MoDrNVEFDt8vW+JMHxKCotfPTlOSySG8R5YQZzc5E4tysbvN1ybTGvqIjlQTeqZ4fGo8tthOjnNHzyBr41RFAqSkaR4attgy4YPAsZBkxTYlCpMWCObuTp+ZgJszCdJ3BnJPXNYyxDFN9WeGvYuShJJ4fKxJwlyty7kDmoIOnHLOwfvBhBHlQnMGqSlVQ9rc7G5Eymj+tniI4eSyqRTr8y3U7M0OFjfZumXGghIqOKtdJkClBe6jLejtpLA0DP59kGuS4E40uvK1wM07/Qjk2E/TzzAQ8ZbuT6DwMd3VNYySiVTzFQY0amq2tOKw297BpDDKx5HGsbg5+7IJlMAR431rYnXVn2yK5Tc0QzZyztL+JrBq28dvI4pi0FeyxYT1JjROeOQ1fGgJYOu2d68j8ne1wFuF/YhMF61u10YpSnEwFCGJHHv1O060z6jcf3xl95MidRiyN2Q6064fsxqifaBuiSWVdyuCJlQwGQkuT6Go8I6o=
  app: bprzybylski-jalgoarena-ui
  on:
    repo: bartpr/JAlgoArena-UI
addons:
  code_climate:
    repo_token: 9e2995be6eae3d6663fd00f8db738c4bf306f9f7779c8f1c4fb0f5d0d56c17e0
